- name: clone dotfiles
  git:
    repo: https://github.com/Xe/dotfiles
    dest: ~/code/dotfiles
  ignore_errors: yes

- name: install dotfiles
  shell: '"cd ~/code/dotfiles && ./setup.sh" creates=~/.zshrc'
