repopath: github.com/Xe/cqbot  # repo path for mounting $CURDIR
golang:   true              # Go has a more opinionated package store
ssh:      true               # pass through ssh keys?
user:     xena               # user in the docker container
projname: cqbot              # project name

# Overlay is the dockerfile to overlay into this for dev establish
overlay: |
  FROM xena/dev-moonscript
  RUN moonrocks install luajson &&\
      moonrocks install luasocket
